name: Practice Phlow
on: push
jobs:
    Lintesteploy:
        runs-on: ubuntu-latest
        steps:
            - name: Getting Code
              uses: actions/checkout@v3
            - name: Install npm
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Linting
              run: npm run lint
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploying
              run: echo "Deploying..."